### PR TITLE
Fix path of script interpreter

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I tried to get the cron job to run on Debian. I had to do two things to make it work:

1. Fix path of script interpreter to python3
2. Manually make the script executable: `sudo chmod +x datacheck.py`

I hope this fixes the issue 🚀

### CODE REVIEW

**Comment by piratenpanda** [comment]
Thanks

**Comment by piratenpanda** [comment]
I still don't understand why all this is necessary when manually running it works just fine. Cron runs this script:
`cd ...bla.../datacheck
python3 ..bla.../datacheck/datacheck.py`

**Comment by KristjanESPERANTO** [comment]
I still don't understand it either 🤔 It still doesn't work.

Did you made the cron script executable: `sudo chmod +x datacheck-cronscript.sh`

**Comment by piratenpanda** [comment]
Yes it is. Manually executing it works fine. Maybe it's some kind of time-out/runtime killer as it takes quite long.

**Comment by piratenpanda** [comment]
It seems to run fine as my logger says it completed the following times:
```Sun Feb 12 12:00:03 AM UTC 2023
Mon Feb 13 12:00:02 AM UTC 2023
Tue Feb 14 12:07:32 AM UTC 2023
Wed Feb 15 12:06:55 AM UTC 2023
Thu Feb 16 12:14:34 AM UTC 2023
Fri Feb 17 12:00:02 AM UTC 2023
Sat Feb 18 12:00:03 AM UTC 2023
Sun Feb 19 12:00:03 AM UTC 2023

**Comment by KristjanESPERANTO** [comment]
That's strange. I created the cron job without any script in between. Maybe try it like this:
`* 23 * * * /var/www/html/veggiekarte/datacheck/datacheck.py`

**Pull request merged**
