### PR TITLE
Refactor refresh.py

### PR DESCRIPTION
**Pull request by codedust**
- use urllib3 instead of urllib
- use json instead of simplejson
- some more refactoring

### CODE REVIEW

**Comment by codedust** [comment]
Wow. That was quick. ;)

**Comment by piratenpanda** [comment]
Now my PhD time is over I hope I can at least invest some time for pull requests ;)

**Comment by piratenpanda** [comment]
Traceback (most recent call last):
  File "refresh.py", line 242, in <module>
    write_data(osm_data)
  File "refresh.py", line 234, in write_data
    f.write('  L.marker([%s, %s], {"title": "%s", icon: icon_%s}).bindPopup("%s").addTo(markers);\n' % (lat, lon, name, icon, popup))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 228: ordinal not in range(128)

**Comment by piratenpanda** [comment]
this is what happens after running refresh.py

**Comment by codedust** [comment]
Hmm. Did you use `python2` or `python3`?

**Comment by piratenpanda** [comment]
Probably python3 is the default on uberspace (which doesn't have urlib3 unfortunately). I'll try running it with python2 right now

**Comment by piratenpanda** [comment]
Ok doesn't work either

**Comment by codedust** [comment]
python3 works for me. Could you double-check your python-version?

**Comment by piratenpanda** [comment]
Ok i managed to install urllib3 now, let's rerun this

**Comment by piratenpanda** [comment]
ok works fine now

**Comment by piratenpanda** [comment]
btw thanks for the work! :)

**Comment by codedust** [comment]
np

Added another PR for python version checking ;)

**Comment by codedust** [comment]
np

Added another PR for python version checking ;)

**Pull request merged**
