### PR TITLE
Discard disused elements + minor changes

### LINKED ISSUE #109: shouldn't show disused: restaurants
I noticed that veggiekarte shows restaurants that are tagged with `disused:`, e.g. node 9429821162 (Veggie Hut, `disused:amenity=restaurant`).

`disused:` items are hidden in most OSM viewers. It would be better to let OpenVegeMap uses the same behaviour.

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
This should fix #109.

### CODE REVIEW

**Comment by piratenpanda** [comment]
Thanks!

**Comment by piratenpanda** [comment]
https://www.veggiekarte.de/?lang=en#19.00000/22.33227/114.16422 still shows for me unfortunately

**Comment by KristjanESPERANTO** [comment]
When I go to the link, "Veggie Hut" is no longer there. Is it maybe still in your cache?

**Comment by piratenpanda** [comment]
Ha, now it's gone. I actually thought having cleared the cache before.. Sorry for the noise, seems fine.

**Comment by KristjanESPERANTO** [comment]
No problem at all!

**Pull request merged**
