### PR TITLE
Introduce data validation

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
This adds a map and a table as tools to improve data quality. What do you think about it?

To start the data check, `./datacheck/datacheck.py` must be executed. Since this is a larger process, I would recommend doing this only once a day.

### CODE REVIEW

**Comment by piratenpanda** [comment]
Let's merge and try

**Comment by piratenpanda** [comment]
Cronjob is set to @daily

**Comment by piratenpanda** [comment]
Looks very nice, thank you!

**Comment by KristjanESPERANTO** [comment]
Thanks for the praise! :smiley: 

Unfortunately, the data is not updated. Can you trigger `datacheck.py` manually to see if it throws error messages?

**Comment by piratenpanda** [comment]
I was missing email_validator in my python install. Should be fine now

**Pull request merged**
